ReseptiHaku/Models/Reseptit.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReseptiHaku.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reseptit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reseptit()
        {
            this.MenuVaihde = new HashSet<MenuVaihde>();
            this.ReseptienAinesosienVaihde = new HashSet<ReseptienAinesosienVaihde>();
            this.ReseptienVaiheidenLista = new HashSet<ReseptienVaiheidenLista>();
        }
    
        public int ReseptiID { get; set; }
        public string ReseptinNimi { get; set; }
        public Nullable<int> AnnosKoko { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MenuVaihde> MenuVaihde { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReseptienAinesosienVaihde> ReseptienAinesosienVaihde { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReseptienVaiheidenLista> ReseptienVaiheidenLista { get; set; }
    }
}

ReseptiHaku/Controllers/ReseptitController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ReseptiHaku.Models;

namespace ReseptiHaku.Controllers
{
    public class ReseptitController : Controller
    {
        private ReseptiHakuEntities2 db = new ReseptiHakuEntities2();

        // GET: Reseptit
        public ActionResult Index()
        {
            return View(db.Reseptit.ToList());
        }

        // GET: Reseptit/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reseptit reseptit = db.Reseptit.Find(id);
            if (reseptit == null)
            {
                return HttpNotFound();
            }
            return View(reseptit);
        }

        // GET: Reseptit/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Reseptit/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ReseptiID,ReseptinNimi,AnnosKoko")] Reseptit reseptit)
        {
            if (ModelState.IsValid)
            {
                db.Reseptit.Add(reseptit);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(reseptit);
        }

        // GET: Reseptit/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reseptit reseptit = db.Reseptit.Find(id);
            if (reseptit == null)
            {
                return HttpNotFound();
            }
            return View(reseptit);
        }

        // POST: Reseptit/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ReseptiID,ReseptinNimi,AnnosKoko")] Reseptit reseptit)
        {
            if (ModelState.IsValid)
            {
                db.Entry(reseptit).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(reseptit);
        }

        // GET: Reseptit/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reseptit reseptit = db.Reseptit.Find(id);
            if (reseptit == null)
            {
                return HttpNotFound();
            }
            return View(reseptit);
        }

        // POST: Reseptit/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Reseptit reseptit = db.Reseptit.Find(id);
            db.Reseptit.Remove(reseptit);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ReseptiHaku/Controllers/ReseptitKLController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ReseptiHaku.Models;
using ReseptiHaku.ViewModels;

namespace ReseptiHaku.Controllers
{
    public class ReseptitKLController : Controller
    {
        private ReseptiHakuEntities2 db = new ReseptiHakuEntities2();

        public ActionResult Reseptit()
        {
            var reseptit = from r in db.Reseptit
                           select r;

            return View(reseptit.ToList());
        }

        //// GET: Reseptit/
        //public ActionResult _ModalEdit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Reseptit reseptit = db.Reseptit.Find(id);
        //    if (reseptit == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    ViewBag.ReseptiVaiheID = new SelectList(db.ReseptienVaiheet, "ReseptiVaiheID", "ReseptiVaihe", reseptit.ReseptiID);
        //    //ViewBag.EmployeeID = new SelectList(db.Employees, "EmployeeID", "LastName", orders.EmployeeID);
        //    //ViewBag.ShipVia = new SelectList(db.Shippers, "ShipperID", "CompanyName", orders.ShipVia);
        //    return PartialView("_ModalEdit", reseptit);
        //}

        //// POST: Orders/Edit/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult _ModalEdit([Bind(Include = "ReseptiID,ReseptienVaiheidenLista.ReseptiVaiheID,ReseptienVaiheet.ReseptiVaihe")] Reseptit reseptit)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(reseptit).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    ViewBag.ReseptiVaiheID = new SelectList(db.ReseptienVaiheet, "ReseptiVaiheID", "ReseptiVaihe", reseptit.ReseptiID);
        //    //ViewBag.EmployeeID = new SelectList(db.Employees, "EmployeeID", "LastName", orders.EmployeeID);
        //    //ViewBag.ShipVia = new SelectList(db.Shippers, "ShipperID", "CompanyName", orders.ShipVia);
        //    return PartialView("_ModalEdit", reseptit);
        //}

        public ActionResult ReseptitYhteenveto()
        {
            var reseptitYhteenveto = from r in db.Reseptit
                                     join rv in db.ReseptienAinesosienVaihde on r.ReseptiID equals rv.ReseptiID
                                     join rl in db.ReseptienAinesosaLista on rv.ReseptiAinesosaListaID equals rl.ReseptiAinesosaListaID
                                     join ra in db.RaakaAineet on rl.RaakaAineID equals ra.RaakaAineID
                                     join ml in db.MittayksikkoLista on rl.MittayksikkoID equals ml.MittayksikkoID
                                     join k in db.Kategoriat on ra.KategoriaID equals k.KategoriaID
                                     join rvl in db.ReseptienVaiheidenLista on r.ReseptiID equals rvl.ReseptiID
                                     join rev in db.ReseptienVaiheet on rvl.ReseptiVaiheID equals rev.ReseptiVaiheID
                                     //where-lause
                                     //orderby-lause
                                     select new ReseptitData
                                     {
                                         ReseptiID = r.ReseptiID,
                                         ReseptinNimi = r.ReseptinNimi,
                                         AnnosKoko = r.AnnosKoko,
                                         LoginID = r.LoginID,
                                         Julkinen = r.Julkinen,
                                         RiviID = rv.RiviID,
                                         ReseptiAinesosaListaID = rl.ReseptiAinesosaListaID,
                                         RaakaAineID = ra.RaakaAineID,
                                         Maara = rl.Maara,
                                         MittayksikkoID = ml.MittayksikkoID,
                                         RaakaAine = ra.RaakaAine,
                                         KategoriaID = k.KategoriaID,
                                         Mittayksikko = ml.Mittayksikko,
                                         MittayksikkoSelite = ml.MittayksikkoSelite,
                                         Kategoria = k.Kategoria,
                                         ReseptiVaiheID = rev.ReseptiVaiheID,
                                         ReseptiVaihe = rev.ReseptiVaihe
                                     };
            return View(reseptitYhteenveto);

        }


        // GET: ReseptitKL
        public ActionResult Index()
        {
            var reseptit = db.Reseptit.Include(r => r.Logins)/*.Include(r => r.ReseptienVaiheidenLista.Select(q => q.ReseptienVaiheet))*/;
            return View(reseptit.ToList());
        }

        // GET: ReseptitKL/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reseptit reseptit = db.Reseptit.Find(id);
            if (reseptit == null)
            {
                return HttpNotFound();
            }

            //------Raaka-aineet, määrät ja mittayksiköt------
            // Sijoitetaan ReseptienAineet taulusta kyseisen ReseptiID:n mukaiset vaiheet ViewBagiin
            List<ReseptienAinesosaLista> lstAineet = new List<ReseptienAinesosaLista>();

            var aineLista = from ral in db.ReseptienAinesosaLista
                            join rav in db.ReseptienAinesosienVaihde on ral.ReseptiAinesosaListaID equals rav.ReseptiAinesosaListaID
                            join ml in db.MittayksikkoLista on ral.MittayksikkoID equals ml.MittayksikkoID
                            join ra in db.RaakaAineet on ral.RaakaAineID equals ra.RaakaAineID
                            where rav.ReseptiID == id
                            select ral;



            foreach (ReseptienAinesosaLista aine in aineLista)
            {
                ReseptienAinesosaLista yksiAine = new ReseptienAinesosaLista();
                yksiAine.RaakaAineID = aine.RaakaAineID;
                //yksiAine.RaakaAine = aine.RaakaAineet.RaakaAine;
                yksiAine.Maara = aine.Maara;
                yksiAine.MittayksikkoID = aine.MittayksikkoID;
                //yksiAine.MittayksikkoLista.Mittayksikko = aine.MittayksikkoLista.Mittayksikko;
                lstAineet.Add(yksiAine);
            }

            ViewBag.ReseptiAineetBag = lstAineet;

            // ------Reseptien vaiheet------
            // Sijoitetaan ReseptienVaiheet taulusta kyseisen ReseptiID:n mukaiset vaiheet ViewBagiin
            List<ReseptienVaiheet> lstVaiheet = new List<ReseptienVaiheet>();

            var vaiheLista = from resv in db.ReseptienVaiheet
                             join resvl in db.ReseptienVaiheidenLista on resv.ReseptiVaiheID equals resvl.ReseptiVaiheID
                             where resvl.ReseptiID == id
                             select resv;

            //ReseptienVaiheet tyhjaVaiheet = new ReseptienVaiheet();
            //tyhjaVaiheet.ReseptiVaiheID = 0;
            //tyhjaVaiheet.ReseptiVaihe = "";
            //lstVaiheet.Add(tyhjaVaiheet);

            foreach (ReseptienVaiheet vaihe in vaiheLista)
            {
                ReseptienVaiheet yksiVaihe = new ReseptienVaiheet();
                yksiVaihe.ReseptiVaiheID = vaihe.ReseptiVaiheID;
                yksiVaihe.ReseptiVaihe = vaihe.ReseptiVaihe;
                lstVaiheet.Add(yksiVaihe);
            }
            
            ViewBag.ReseptiVaiheetBag = lstVaiheet;

            return View(reseptit);
        }

        // GET: ReseptitKL/Create
        public ActionResult Create()
        {
            ViewBag.LoginID = new SelectList(db.Logins, "LoginID", "UserName");
            return View();
        }

        // POST: ReseptitKL/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ReseptiID,ReseptinNimi,AnnosKoko,LoginID,Julkinen")] Reseptit reseptit)
        {
            if (ModelState.IsValid)
            {
                db.Reseptit.Add(reseptit);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.LoginID = new SelectList(db.Logins, "LoginID", "UserName", reseptit.LoginID);
            return View(reseptit);
        }

        // GET: ReseptitKL/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reseptit reseptit = db.Reseptit.Find(id);
            if (reseptit == null)
            {
                return HttpNotFound();
            }
            ViewBag.LoginID = new SelectList(db.Logins, "LoginID", "UserName", reseptit.LoginID);
            return View(reseptit);
        }

        // POST: ReseptitKL/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ReseptiID,ReseptinNimi,AnnosKoko,LoginID,Julkinen")] Reseptit reseptit)
        {
            if (ModelState.IsValid)
            {
                db.Entry(reseptit).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

ReseptiHaku/Views/ReseptitKL/Create.cshtml
@model ReseptiHaku.Models.Reseptit

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Reseptit</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ReseptinNimi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReseptinNimi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReseptinNimi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AnnosKoko, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AnnosKoko, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AnnosKoko, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LoginID, "LoginID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("LoginID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LoginID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Julkinen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Julkinen)
                    @Html.ValidationMessageFor(model => model.Julkinen, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ReseptiHaku/Views/ReseptitKL/Delete.cshtml
@model ReseptiHaku.Models.Reseptit

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Reseptit</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ReseptinNimi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReseptinNimi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AnnosKoko)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AnnosKoko)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Julkinen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Julkinen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Logins.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Logins.UserName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ReseptiHaku/Views/ReseptitKL/Details.cshtml
@model ReseptiHaku.Models.Reseptit

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Reseptit</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>@Html.DisplayNameFor(model => model.ReseptinNimi)</dt>

        <dd>@Html.DisplayFor(model => model.ReseptinNimi)</dd>

        <dt>@Html.DisplayNameFor(model => model.AnnosKoko)</dt>

        <dd>@Html.DisplayFor(model => model.AnnosKoko)</dd>

        <dt>@Html.DisplayNameFor(model => model.Julkinen)</dt>

        <dd>@Html.DisplayFor(model => model.Julkinen)</dd>

        <dt>@Html.DisplayNameFor(model => model.Logins.UserName)</dt>

        <dd>@Html.DisplayFor(model => model.Logins.UserName)</dd>

        <div class"input-group">
            <ul>
                @foreach (var aine in ViewBag.ReseptiAineetBag)
                {
                    <li>@aine.RaakaAineID @aine.Maara @aine.MittayksikkoID</li>
                    @*<li>@aine.Maara</li>
                    <li>@aine.MittayksikkoID</li>*@
                }
            </ul>
            <ul>
                @foreach (var vaihe in ViewBag.ReseptiVaiheetBag)
                {
                    <li>@vaihe.ReseptiVaihe</li>
                }
            </ul>
        </div>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ReseptiID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ReseptiHaku/Views/ReseptitKL/_ModalEdit.cshtml
@model ReseptiHaku.Models.Reseptit



@*modal-ikkuna*@
<div class="modal fade" id="ModalReseptiEdit">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">

            <div class="modal-header">
                <h4 class="modal-title">Reseptin muokkaus</h4>
            </div>

            <div class="modal-body">
                @using (Html.BeginForm("_ModalEdit", "ReseptitKL", FormMethod.Post, new { id = "editForm" }))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <h4>Reseptit</h4>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.ReseptiID)
                    </div>
                    <div class="row">
                        <div class="col-sm-6">

                            <div class="form-group">
                                @Html.LabelFor(model => model.ReseptiID, "ReseptiID", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.DropDownList("ReseptiID", null, htmlAttributes: new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.ReseptiID, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.ReseptienVaiheet.ReseptiVaihe, "ReseptiVaihe", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.DropDownList("EmployeeID", null, htmlAttributes: new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.ReseptiVaiheID, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            @*<div class="form-group">
                                @Html.LabelFor(model => model.OrderDate, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.OrderDate, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.OrderDate, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.RequiredDate, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.RequiredDate, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.RequiredDate, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.ShippedDate, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.ShippedDate, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.ShippedDate, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.ShipVia, "ShipVia", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.DropDownList("ShipVia", null, htmlAttributes: new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.ShipVia, "", new { @class = "text-danger" })
                                </div>
                            </div>*@
                        </div>

                        <div class="col-sm-6">

                            <div class="form-group">
                                @Html.LabelFor(model => model.Freight, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Freight, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Freight, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            @*<div class="form-group">
                                @Html.LabelFor(model => model.ShipName, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.ShipName, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.ShipName, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.ShipAddress, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.ShipAddress, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.ShipAddress, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.ShipCity, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.ShipCity, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.ShipCity, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.ShipRegion, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.ShipRegion, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.ShipRegion, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.ShipPostalCode, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.ShipPostalCode, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.ShipPostalCode, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.ShipCountry, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.ShipCountry, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.ShipCountry, "", new { @class = "text-danger" })
                                </div>
                            </div>*@
                        </div>
                    </div>
                }
            </div>

            <div class="modal-footer">
                <button type="submit" class="btn btn-primary" form="editForm"><i class="fas fa-check"></i></button>
                <a href="@Url.Action("Reseptit", "ReseptitKL")" class="btn btn-primary"><i class="fas fa-times"></i></a>
            </div>

        </div>
    </div>
</div>